### ISSUE TITLE
🐛 Bug Report: Error in Storage API createFile function of dotnet SDK

### ISSUE THREAD

**Issue by abhishek-visitnow** [appwrite/sdk-for-dotnet#49]
### 👟 Reproduction steps

I'm trying to upload a file greater than 4 Mb. Following code is working when the size of file is less than 4 mb.

Using dotnet sdk v0.8.3

```
File myfile = await storage.CreateFile(
                 bucketId: "bucket-id",
                 fileId: ID.Unique(),
                 file: InputFile.FromBytes(
                     Encoding.UTF8.GetBytes(json),
                     "filename.json,
                     "application/json"
                     ),
                 permissions: permissions! // optional
             );
```

### 👍 Expected behavior

It should upload the file.

### 👎 Actual Behavior

Getting following error:
```
Appwrite.AppwriteException: The requested route was not found. Please refer to the API docs and try again.
   at Appwrite.Client.Call[T](String method, String path, Dictionary`2 headers, Dictionary`2 parameters, Func`2 convert)
   at Appwrite.Client.ChunkedUpload[T](String path, Dictionary`2 headers, Dictionary`2 parameters, Func`2 converter, String paramName, String idParamName, Action`1 onProgress)
   at DotNetRuntime.Handler.Main(RuntimeContext Context) in /usr/local/server/src/Index.cs:line 67
   at DotNetRuntime.Program.Action(HttpRequest request) in /usr/local/server/src/Program.cs:line 194
```

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@adityaoberai looked into this and noticed we're still checking for `"unique()"`

https://github.com/appwrite/sdk-for-dotnet/blob/e0ca49126bb8cf97b0826c8acd7af12b244ea920/Appwrite/Client.cs#L408

even though `ID.unique()` doesn't return `"unique()"` anymore:

https://github.com/appwrite/sdk-for-dotnet/blob/e0ca49126bb8cf97b0826c8acd7af12b244ea920/Appwrite/ID.cs#L22-L35

Looks like we're going to need to fix this in the following SDKs:

- [ ] [android](https://github.com/appwrite/sdk-for-android/blob/85fac9dedd90eefe8407382cdd9f54b436862703/library/src/main/java/io/appwrite/Client.kt#L401-L412)
- [ ] [ruby](https://github.com/appwrite/sdk-for-ruby/blob/c3777a7fa6a95373bc4a2aa05813eaa76fdbda9a/lib/appwrite/client.rb#L190-L200)
- [ ] [dotnet](https://github.com/appwrite/sdk-for-dotnet/blob/e0ca49126bb8cf97b0826c8acd7af12b244ea920/Appwrite/Client.cs#L408)
- [ ] [kotlin](https://github.com/appwrite/sdk-for-kotlin/blob/80cfc9b7ad7c656cfec9ad68f467964c79eebaab/src/main/kotlin/io/appwrite/Client.kt#L430-L441)
